# Generated by Django 3.2.8 on 2021-10-25 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Licitante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj_lic', models.IntegerField(verbose_name='CNPJ')),
                ('nome_lic', models.CharField(max_length=50, verbose_name='Licitante')),
                ('cidade_lic', models.CharField(max_length=25, verbose_name='Cidade')),
                ('uf_lic', models.CharField(choices=[('SP', 'sp'), ('RJ', 'rj'), ('BH', 'bh'), ('RO', 'ro'), ('AM', 'am'), ('SC', 'sc'), ('PA', 'pa')], default='SP', max_length=2, verbose_name='UF')),
            ],
        ),
        migrations.CreateModel(
            name='Orgao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Orgão')),
                ('cidade', models.CharField(max_length=25, verbose_name='Cidade')),
                ('uf', models.CharField(choices=[('SP', 'sp'), ('RJ', 'rj'), ('BH', 'bh'), ('RO', 'ro'), ('AM', 'am'), ('SC', 'sc'), ('PA', 'pa')], default='SP', max_length=2, verbose_name='UF')),
            ],
        ),
        migrations.CreateModel(
            name='Licitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_certame', models.IntegerField(verbose_name='Numero do Pregão')),
                ('certame', models.CharField(max_length=50, verbose_name='Licitação')),
                ('data_publicacao', models.DateField(max_length=10, verbose_name='Data da Plubicação')),
                ('data_abertura', models.DateField(max_length=10, verbose_name='Data da Abertura')),
                ('numero_do_item', models.IntegerField(verbose_name='Numero do Item')),
                ('desc_item', models.TextField(verbose_name='Descrição')),
                ('qtd_item', models.DecimalField(decimal_places=4, max_digits=5, verbose_name='Quantidade')),
                ('unidade', models.CharField(max_length=2, verbose_name='Unidade')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Preço')),
                ('marca', models.CharField(max_length=20, verbose_name='Marca')),
                ('orgao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sclapp.orgao')),
            ],
        ),
    ]
